"""添加用户邮箱确认字段

Revision ID: b9b8dd3c5349
Revises: 91e2b4fbb845
Create Date: 2019-09-13 17:08:39.420423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b8dd3c5349'
down_revision = '91e2b4fbb845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
